print("Python strings operators and methods...\n\n")


str = "ganpati bappa moryaa...."
str2 = "har har mahadev..."
print(str[4:11]) #it prints characters from 4th index to 11th index...
print(str[:16]) #it prints characters 0 index to 16th index..
print(str[6:]) #it prints characters 6th index to the end ...


print(str.capitalize())  #it capitalize the string means it automatically replace first character capital...
print(str.upper()) #it replace all the characters capital in the string...
print(max(str))  #it prints the highest value (ASCII)
print(str + str2)  #plus(+) will marge two strings...
print(str*2)  #asterics(*) will multiple the string....
